# Generated by Django 2.2.17 on 2020-12-16 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='著者'),
            preserve_default=False,
        ),
    ]
